#pragma once

#include "literals.hpp"
//这是存放具体的尺寸的地方
namespace rune {

constexpr int MAT_WIDTH = 1280;  //图片宽度
constexpr int MAT_HEIGHT = 1024; //图片高度

constexpr double SMALL_ARMOR_WIDTH = 135_mm;
constexpr double SMALL_ARMOR_HEIGHT = 55_mm;
constexpr double BIG_ARMOR_WIDTH = 225_mm;
constexpr double BIG_ARMOR_HEIGHT = 55_mm;
constexpr double RUNE_ARMOR_WIDTH = 160_mm;
constexpr double RUNE_ARMOR_HEIGHT = 154_mm;

constexpr double RUNE_ARMOR_RADIUS = 150_mm;                //待测,装甲板半径
constexpr double RUNE_ARMOR_OUTER_LIGHTBAR_WIDTH = 170_mm;  //待测，装甲板灯条外接四边形宽度
constexpr double RUNE_ARMOR_OUTER_LIGHTBAR_LENGTH = 372_mm; //待测，装甲板灯条外接四边形长度
constexpr double RUNE_ARMOR_INSIDE_LIGHTBAR_LENGTH = 510_mm;
constexpr double RUNE_ARMOR_INSIDE_LIGHTBAR_WIDTH = 372_mm;

constexpr double RUNE_ARMOR_LIGHTBAR_OUTER2CENTER =
    823.65_mm; //待测，装甲板外侧灯条外接四边形中心到标志中心的距离
constexpr double RUNE_ARMOR_LIGHTBAR_INSIDE2CENTER =
    582.76_mm; //待测，装甲板内侧灯条外接四边形中心到标志中心的距离

constexpr int MIN_AREA = MAT_WIDTH * MAT_HEIGHT * 5e-6;

constexpr double LENGTH_ERROR_RATE_MIN = 1. - .25; //长度最大与最小误差
constexpr double LENGTH_ERROR_RATE_MAX = 1. + .25;
constexpr double LENGTH_RATIO_ERROR_RATE_MIN = LENGTH_ERROR_RATE_MIN / LENGTH_ERROR_RATE_MAX;
constexpr double LENGTH_RATIO_ERROR_RATE_MAX = LENGTH_ERROR_RATE_MAX / LENGTH_ERROR_RATE_MIN;
constexpr double AREA_RATIO_ERROR_RATE_MIN =
    LENGTH_RATIO_ERROR_RATE_MIN * LENGTH_RATIO_ERROR_RATE_MIN; //
constexpr double AREA_RATIO_ERROR_RATE_MAX =
    LENGTH_RATIO_ERROR_RATE_MAX * LENGTH_RATIO_ERROR_RATE_MAX;

constexpr double CENTER_RADIUS = 45_mm;
// constexpr double CENTER_RADIUS = 46_mm;
constexpr double CENTER_DISTANCE = 7480_mm;
constexpr double CENTER_DISTANCE_VERTICAL = 1535_mm;
constexpr double CENTER_DISTANCE_HORIZONTAL = 7320_mm;
constexpr double CENTER_AREA = M_PI * CENTER_RADIUS * CENTER_RADIUS;
constexpr double CENTER_RATIO = 1.;
constexpr double CENTER_RATIO_MIN = CENTER_RATIO * LENGTH_RATIO_ERROR_RATE_MIN;
constexpr double CENTER_RATIO_MAX = CENTER_RATIO * LENGTH_RATIO_ERROR_RATE_MAX;

constexpr double ARMOR_WIDTH = 127_mm;
constexpr double ARMOR_LENGTH = 230_mm;
constexpr double ARMOR_AREA = ARMOR_WIDTH * ARMOR_LENGTH;
constexpr double ARMOR_ASPECT_RATIO = ARMOR_LENGTH / ARMOR_WIDTH;
constexpr double ARMOR_ASPECT_RATIO_MIN = ARMOR_ASPECT_RATIO * LENGTH_RATIO_ERROR_RATE_MIN;
constexpr double ARMOR_ASPECT_RATIO_MAX = ARMOR_ASPECT_RATIO * LENGTH_RATIO_ERROR_RATE_MAX;

constexpr double LEAF_WIDTH = 325_mm;
constexpr double LEAF_LENGTH = 650_mm;
constexpr double LEAF_AREA = LEAF_WIDTH * LEAF_LENGTH;
constexpr double LEAF_ASPECT_RATIO = LEAF_LENGTH / LEAF_WIDTH;
constexpr double LEAF_ASPECT_RATIO_MIN = LEAF_ASPECT_RATIO * LENGTH_RATIO_ERROR_RATE_MIN;
constexpr double LEAF_ASPECT_RATIO_MAX = LEAF_ASPECT_RATIO * LENGTH_RATIO_ERROR_RATE_MAX;

constexpr double AREA_RATIO = ARMOR_AREA / LEAF_AREA;
constexpr double AREA_RATIO_MIN = AREA_RATIO * AREA_RATIO_ERROR_RATE_MIN;
constexpr double AREA_RATIO_MAX = AREA_RATIO * AREA_RATIO_ERROR_RATE_MAX;

constexpr double RUNE_ROTATE_A_MIN = 0.780;
constexpr double RUNE_ROTATE_A_MAX = 1.045;
constexpr double RUNE_ROTATE_A_MEAN = (RUNE_ROTATE_A_MAX + RUNE_ROTATE_A_MIN) / 2;
constexpr double RUNE_ROTATE_O_MIN = 1.884;
constexpr double RUNE_ROTATE_O_MAX = 2.000;
constexpr double RUNE_ROTATE_O_MEAN = (RUNE_ROTATE_O_MAX + RUNE_ROTATE_O_MIN) / 2;
constexpr double RUNE_ROTATE_A_ADD_B = 2.090;

constexpr double RUNE_ACTIVATION_HORIZONTAL_MIN_DISTANCE = 6439_mm;
constexpr double RUNECENTER_ACTIVATION_VERTICAL_DISTANCE = 1441_mm;

constexpr double RUNE_ARMOR_OUTER_LIGHTBAR_RATIO =
    RUNE_ARMOR_OUTER_LIGHTBAR_LENGTH / RUNE_ARMOR_OUTER_LIGHTBAR_WIDTH; //装甲板灯条外接四边形长宽比
constexpr double RUNE_ARMOR_OUTER_LIGHTBAR_RATIO_MAX =
    RUNE_ARMOR_OUTER_LIGHTBAR_RATIO * LENGTH_ERROR_RATE_MAX;
constexpr double RUNE_ARMOR_OUTER_LIGHTBAR_RATIO_MIN =
    RUNE_ARMOR_OUTER_LIGHTBAR_RATIO * LENGTH_ERROR_RATE_MIN;

constexpr double RUNE_ARMOR_INSIDE_LIGHTBAR_RATIO = RUNE_ARMOR_INSIDE_LIGHTBAR_LENGTH
    / RUNE_ARMOR_INSIDE_LIGHTBAR_WIDTH; //装甲板灯条外接四边形长宽比
constexpr double RUNE_ARMOR_INSIDE_LIGHTBAR_RATIO_MAX =
    RUNE_ARMOR_INSIDE_LIGHTBAR_RATIO * LENGTH_ERROR_RATE_MAX;
constexpr double RUNE_ARMOR_INSIDE_LIGHTBAR_RATIO_MIN =
    RUNE_ARMOR_INSIDE_LIGHTBAR_RATIO * LENGTH_ERROR_RATE_MIN;

constexpr double RUNE_ARMOR_LIGHTBAR2CENTER_RATIO = RUNE_ARMOR_LIGHTBAR_OUTER2CENTER
    / RUNE_ARMOR_LIGHTBAR_INSIDE2CENTER; //外侧灯条与内侧灯条到标志中心的距离比
constexpr double RUNE_ARMOR_LIGHTBAR2CENTER_RATIO_MAX =
    RUNE_ARMOR_LIGHTBAR2CENTER_RATIO * LENGTH_RATIO_ERROR_RATE_MAX;
constexpr double RUNE_ARMOR_LIGHTBAR2CENTER_RATIO_MIN =
    RUNE_ARMOR_LIGHTBAR2CENTER_RATIO * LENGTH_RATIO_ERROR_RATE_MIN;

constexpr double RUNE_LIGHTBAR_SYMBOL_RATIO =
    (RUNE_ARMOR_INSIDE_LIGHTBAR_WIDTH * RUNE_ARMOR_INSIDE_LIGHTBAR_LENGTH)
    / (CENTER_RADIUS * CENTER_RADIUS * M_PI); //装甲板灯条外接四边形面积与装甲板标识符面积比
constexpr double RUNE_LIGHTBAR_SYMBOL_RATIO_MAX =
    RUNE_LIGHTBAR_SYMBOL_RATIO * LENGTH_RATIO_ERROR_RATE_MAX * LENGTH_RATIO_ERROR_RATE_MAX;
constexpr double RUNE_LIGHTBAR_SYMBOL_RATIO_MIN =
    RUNE_LIGHTBAR_SYMBOL_RATIO * LENGTH_RATIO_ERROR_RATE_MIN * LENGTH_RATIO_ERROR_RATE_MIN;

constexpr double RUNE_LIGHTBAR_OUTER_INSIDE_RATIO =
    (RUNE_ARMOR_OUTER_LIGHTBAR_WIDTH * RUNE_ARMOR_OUTER_LIGHTBAR_LENGTH)
    / (RUNE_ARMOR_INSIDE_LIGHTBAR_LENGTH * RUNE_ARMOR_INSIDE_LIGHTBAR_WIDTH
    ); //装甲板外灯条外接四边形面积与（内灯条与符叶外接四边形面积之和）比值
constexpr double RUNE_LIGHTBAR_OUTER_INSIDE_RATIO_MIN =
    RUNE_LIGHTBAR_OUTER_INSIDE_RATIO * LENGTH_RATIO_ERROR_RATE_MIN * LENGTH_RATIO_ERROR_RATE_MIN;
constexpr double RUNE_LIGHTBAR_OUTER_INSIDE_RATIO_MAX =
    RUNE_LIGHTBAR_OUTER_INSIDE_RATIO * LENGTH_RATIO_ERROR_RATE_MAX * LENGTH_RATIO_ERROR_RATE_MAX;

constexpr double RUNE_ARMOR_SYMBOL_RATIO = (RUNE_ARMOR_RADIUS * RUNE_ARMOR_RADIUS)
    / (CENTER_RADIUS * CENTER_RADIUS); //装甲板面积与能量机关标志符面积比
constexpr double RUNE_ARMOR_SYMBOL_RATIO_MAX =
    RUNE_ARMOR_SYMBOL_RATIO * LENGTH_RATIO_ERROR_RATE_MAX * LENGTH_RATIO_ERROR_RATE_MAX;
constexpr double RUNE_ARMOR_SYMBOL_RATIO_MIN =
    RUNE_ARMOR_SYMBOL_RATIO * LENGTH_RATIO_ERROR_RATE_MIN * LENGTH_RATIO_ERROR_RATE_MIN;

constexpr double RUNE_PNP_OUTER_LIGHTBAR_WIDTH = 320_mm; //官方符的尺寸参数
constexpr double RUNE_PNP_INSIDE_LIGHTBAR_WIDTH = 372_mm;
constexpr double RUNE_PNP_RADIUS = 308_mm;
constexpr double RUNE_ARMOR_TO_SYMBOL = 703.205_mm;

// constexpr double RUNE_PNP_OUTER_LIGHTBAR_WIDTH = 310_mm; //实验室符的尺寸参数
// constexpr double RUNE_PNP_INSIDE_LIGHTBAR_WIDTH = 365_mm;
// constexpr double RUNE_PNP_RADIUS = 325_mm;

// constexpr double RUNE_ARMOR_TO_SYMBOL = 578.065_mm; //仿真符的尺寸参数
// constexpr double RUNE_PNP_OUTER_LIGHTBAR_WIDTH = 304.2_mm;
// constexpr double RUNE_PNP_INSIDE_LIGHTBAR_WIDTH = 255.5_mm;
// constexpr double RUNE_PNP_RADIUS = 266.8_mm;

} // namespace rune
